---
# Run a command on a node
- hosts: mwelk-cftest
  remote_user: root
  become: no
- vars:
      - command_variable: "/usr/bin/date > /tmp/ansible-command.log"
  tasks:
      - name: run this command and ignore the result
        shell: "exec {{ command_variable }} || /bin/true"
