---
# Run a command on a node
- hosts: all-servers
  remote_user: root
  become: no
  tasks:
      - name: Loop through a list of commands and execute them
        shell: "exec {{ item }}"
        with_items: "{{ list_of_commands|default([]) }}"
